### PR TITLE
V2 linter api support

### LINKED ISSUE #44: Add lint on the fly option
The readme says this lints on the fly. It doesn't, it lints on save. The scala compiler is slow so lint on save is sensible, but there should be an option to lint on the fly. This issue involves the following tasks:
- [ ] Add option to lint on the fly with default.
- [ ] Add default of false for linting on the fly.
- [ ] Update the Readme to remove the lint on the fly note.

### LINKED ISSUE #62: Getting Timeouts
I'm getting timeouts for projects with more dependencies:

`/Users/franciscog/.atom/packages/linter/lib/linter-registry.js:177 [Linter] Error running scalac Error: Process execution timed out(…)(anonymous function) @ /Users/franciscog/.atom/packages/linter/lib/linter-registry.js:177`

### LINKED ISSUE #82: Support v2 Linter API
In the [v2.3.0 release](https://github.com/steelbrain/linter/releases/tag/v2.3.0) of `linter` support for the v1 API was removed, breaking semver. This means that this provider is no longer supported by the current version of `linter`.

To get this provider working again it will need to be upgrade to the v2 API, a guide for accomplishing that can be found here: [Upgrading to Standard Linter v2](https://github.com/steelbrain/linter/blob/v2.3.0/docs/guides/upgrading-to-standard-linter-v2.md).

Until this is fixed in order to use this provider you will need to downgrade to the last version of `linter` that supports the v1 API, you can do this with `apm install linter@2.2.0`.

### PR DESCRIPTION
**Pull request by vzamanillo**
Fixes #82
Fixes #62
Closes #44

### CODE REVIEW

File: lib/linter-scalac.js [hunk 1]
```diff
@@ -3,30 +3,66 @@
...
+
+const getSeverity = (givenSeverity) => {
+  const severity = givenSeverity.toLowerCase();
+  return VALID_SEVERITY.has(severity) ? severity : 'warning';
+};
 
+const parseFileStdout = (output, regex, filePath, editor) => {
+  const messages = [];
+
+  let match = regex.exec(output, filePath);
```
Comment (Arcanemagus) [inline lib/linter-scalac.js]: Since these are dedicated functions there is no need to pass in the regex as an argument.

File: lib/linter-scalac.js [hunk 2]
```diff
@@ -3,30 +3,66 @@
...
+    });
+    match = regex.exec(output);
+  }
+  return messages;
+};
+
+const parseCompileStdout = (output, regex, filePath) => {
+  const messages = [];
+
+  let match = regex.exec(output);
```
Comment (Arcanemagus) [inline lib/linter-scalac.js]: Again: embed/use the regex directly here.

File: lib/linter-scalac.js [hunk 3]
```diff
@@ -3,35 +3,96 @@
...
+  }
+  if (!glob) {
+    glob = require('glob');
+  }
+  if (!mkdirp) {
+    mkdirp = require('mkdirp');
+  }
+};
+
+const parseFileStdout = (output, filePath, editor) => {
```
Comment (Arcanemagus) [inline lib/linter-scalac.js]: Let's rename this to just `parseFileOutput`.

File: lib/linter-scalac.js [hunk 4]
```diff
@@ -3,35 +3,96 @@
...
+        file: filePath,
+        position: helpers.generateRange(editor, line),
+      },
+    });
+    match = fileRegex.exec(output);
+  }
+  return messages;
+};
+
+const parseCompileStdout = (output, filePath) => {
```
Comment (Arcanemagus) [inline lib/linter-scalac.js]: And this to `parseCompileOutput`.

File: lib/linter-scalac.js [hunk 5]
```diff
@@ -121,12 +184,34 @@ module.exports = {
 
         args.push(filePath);
 
-        const options = { stream: 'stderr', allowEmptyStderr: true };
+        const stdin = editor.getText();
+        const execOptions = {
+          stdin,
+          stream: 'both',
```
Comment (Arcanemagus) [inline lib/linter-scalac.js]: Previously only the `stderr` stream was being used. You're requesting both `stderr` and `stdout` here, but the `stdout` stream isn't actually being used.

Should one of the parse functions below be using that stream's contents instead of the `stderr` contents?

Comment (vzamanillo) [reply lib/linter-scalac.js]: Yep, I was confused about the stream value because I thougth I need both to use stdin.

**Comment by Arcanemagus** [comment]
Only realized a few days ago that all the `minor` version releases for these should have been `major` since it's dropping support for the v1 Linter API... the entire problem that triggered all of this! 🤦‍♂️ 🤣

**Comment by vzamanillo** [comment]
> Only realized a few days ago that all the `minor` version releases for these should have been `major` since it's dropping support for the v1 Linter API... the entire problem that triggered all of this! man_facepalming rofl

I'm sure only you and me know about this... :rofl:
